### ISSUE TITLE
Quick Start lab needs major revisions

### ISSUE THREAD

**Issue by tooda02** [CiscoCloud/Shipped-Learning-Labs#45]
There are some significant issues with the Quick Start lab.  For example:
- The Bootstrapping and Docker path shows a command only for Mac.  Windows and Linux are ignored (Windows has a significantly different command)
- The command shown for Mac has a hardcoded project ID and API token
- The command shown for Mac is incorrect anyway; it's not the "shipped local bootstrap" command that's used for bootstrap
- There's a whole section called "Interact With Vagrant" which is not something we want our users to be doing.  Among other things, we will likely be switching from Vagrant to docker-compose.  Interacting with either should be done through the CLI

This lab needs to be re-thought and probably rewritten.

**Comment by npateriya** [comment]
done
