### ISSUE TITLE
Show alternative install (Powershell install fails on older versions of Windows)

### ISSUE THREAD

**Issue by tooda02** [CiscoCloud/Shipped-Learning-Labs#46]
Windows versions prior to Windows 7 do not contain Powershell, so the install command presented by the UI fails on those platforms.  The Learning Labs should present an alternative installation method (double-clicking on the [shipped-install download link](https://bintray.com/artifact/download/shippedrepos/shipped-install/windows/shipped-install.exe) for users that encounter this issue.

**Comment by npateriya** [comment]
done
