### ISSUE TITLE
Additonal step for build logs, create env and deploy service

### ISSUE THREAD

**Issue by npateriya** [CiscoCloud/Shipped-Learning-Labs#5]
I have updated the basic documentation for Shipped to Describe the remainder of the UI and process for deploying a build to shipped. You can see / review it here. Comments appreciatd. Thanks. https://github.com/CiscoCloud/Shipped-Learning-Labs/blob/master/shipped-101-first-project/src/posts/files/shipped-101-first-project/2.md

These need to be added as steps that user will follow post commit.

**Comment by ObjectiveJoe** [comment]
I believe this is completed.
