### ISSUE TITLE
CMX Doc updates

### ISSUE THREAD

**Issue by npateriya** [CiscoCloud/Shipped-Learning-Labs#6]
As discussed 
1. Move this to end, Advance user section : https://github.com/CiscoCloud/Shipped-Learning-Labs/blob/master/shipped-102-cmx-project/src/posts/files/shipped-102-cmx-project/1.md#open-source-software-used-by-shipped
1. 2.md : Image link broken after this " Compose Your Project to display the list of APIs:"
2.  Add Step 9: To show how to modify code and test locally using "make run"
3. Remove vagrant commands and refer "make run" and "make clean" etc.  
4. Move Code details and Vagrant steps as Advance/optional section.

**Comment by tooda02** [comment]
Closed with https://github.com/CiscoCloud/Shipped-Learning-Labs/commit/b1c98eb1e2731f63229d9aa7c4366c61bb3bf55b
